return {
	PlaceObj('ModItemCode', {
		'name', "ShipmentSquad",
		'CodeFileName', "Code/ShipmentSquad.lua",
	}),
	PlaceObj('ModItemFolder', {
		'name', "Changes",
	}, {
		PlaceObj('ModItemChangeProp', {
			'name', "ChangeProperty",
			'TargetClass', "ShipmentSquadPreset",
			'TargetId', "DiamondShipment",
			'TargetProp', "weight",
			'TargetValue', 50,
		}),
		PlaceObj('ModItemChangeProp', {
			'name', "ChangeProperty",
			'TargetClass', "ShipmentSquadPreset",
			'TargetId', "WeaponShipment",
			'TargetProp', "enemy_squad_def",
			'TargetValue', "ShipmentSquad",
		}),
		PlaceObj('ModItemChangeProp', {
			'name', "ChangeProperty",
			'TargetClass', "ShipmentSquadPreset",
			'TargetId', "DiamondShipment",
			'TargetProp', "enemy_squad_def",
			'TargetValue', "ShipmentSquad",
		}),
		}),
	PlaceObj('ModItemShipmentSquadPreset', {
		EnableConditions = {
			PlaceObj('QuestIsTCEState', {
				Prop = "TCE_OpenB12U",
				QuestId = "U-Bahn",
				Value = true,
			}),
			PlaceObj('QuestIsTCEState', {
				Prop = "TCE_B12Unlock",
				QuestId = "U-Bahn_Helpers",
				Value = true,
			}),
		},
		IntelText = T(384575124383, --[[ModItemShipmentSquadPreset Kompositum58 IntelText]] "A Kompositum58 shipment is carried by a specific enemy. Retrieve it to arm yourself."),
		IntelTitle = T(753201959565, --[[ModItemShipmentSquadPreset Kompositum58 IntelTitle]] "Kompositum58 Shipment"),
		SquadName = T(228530480878, --[[ModItemShipmentSquadPreset Kompositum58 SquadName]] "Kompositum58 Shipment"),
		TimelineEventHint = T(647185259372, --[[ModItemShipmentSquadPreset Kompositum58 TimelineEventHint]] "Intercepting the squad and obtaining the shipment will bring in Kompositum58."),
		TimelineEventText = T(220151368576, --[[ModItemShipmentSquadPreset Kompositum58 TimelineEventText]] "The Kompositum58 shipment will reach <color EmStyle>"),
		TimelineEventTitle = T(126047344031, --[[ModItemShipmentSquadPreset Kompositum58 TimelineEventTitle]] "Kompositum58 Shipment Enroute"),
		badge_icon = "Mod/DiamondBEnhanced/Images/bag58 2",
		enemy_squad_def = "ShipmentSquad",
		group = "Default",
		icon = "Mod/DiamondBEnhanced/Images/bag64",
		id = "Kompositum58",
		intel_icon = "Mod/DiamondBEnhanced/Images/bag58",
		item = "Kompositum58Shipment",
		squad_icon = "Mod/DiamondBEnhanced/Images/bag64 2",
		squad_icon_2 = "Mod/DiamondBEnhanced/Images/bag72",
		weight = 25,
	}),
	PlaceObj('ModItemInventoryItemCompositeDef', {
		'Group', "Valuables",
		'Id', "Kompositum58Shipment",
		'object_class', "ValuableItemContainer",
		'Repairable', false,
		'Icon', "Mod/DiamondBEnhanced/Images/18557-128x128x32",
		'SubIcon', "UI/Icons/Items/kompositum58",
		'DisplayName', T(786856547334, --[[ModItemInventoryItemCompositeDef Kompositum58Shipment DisplayName]] "Kompositum Shipment"),
		'DisplayNamePlural', T(730786364203, --[[ModItemInventoryItemCompositeDef Kompositum58Shipment DisplayNamePlural]] "Kompositum Shipments"),
		'Description', T(899423254887, --[[ModItemInventoryItemCompositeDef Kompositum58Shipment Description]] "A shipment of Kompositum recovered from the enemy."),
		'AdditionalHint', T(339309137675, --[[ModItemInventoryItemCompositeDef Kompositum58Shipment AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> <color 130 128 120>Can be opened to receive the items</color>"),
		'Valuable', 1,
		'Cost', 10000,
		'loot_def', "Kompositum58Shipment",
		'RestockWeight', 0,
	}),
	PlaceObj('ModItemLootDef', {
		group = "System",
		id = "Kompositum58Shipment",
		loot = "all",
		PlaceObj('LootEntryInventoryItem', {
			guaranteed = true,
			item = "Combination_Kompositum58",
			stack_max = 1,
			stack_min = 1,
		}),
		PlaceObj('LootEntryInventoryItem', {
			generate_chance = 50,
			item = "Reanimationsset",
			stack_max = 1,
			stack_min = 1,
		}),
	}),
}